---
title: "Clustering/MDS"
output: html_notebook
---


```{r setup}
library(tidyverse)
library(here)
library(vegan)
library(cowplot)
library(phyloseq)
library(rstan)
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)
source(here("R","sample_posterior.R"))

```

Tijana's code to load the data
```{r}
otutable = read.delim(file = here("private_data","tijana",'Seedlings_ITS2_otutab_ALL.csv'), sep = "\t") #reading the data I want to use
otutabP = otutable[, -1]
rownames(otutabP) = otutable [, 1]

t_otutab <- t(as.matrix(otutabP))

mapping = read.delim(file = here("private_data","tijana","Seedlings_ITS2_year1_mapping.csv"), sep = ",") %>%
  mutate(Replicate_no = gsub("[A-Za-z]","", Replicate))
mapping2 = mapping [,-1] #it is the new mapping file with the proper row names, same as in previous case, here we added names from the mapping
rownames(mapping2) = mapping[,1]
#?order
mapping3 = sample_data(mapping2) #making corrected mapping file a phyloseq object

```


```{r}
set.seed(13248455)
min_depth = min(colSums(otutabP))
t_otus_rarefied = as.data.frame(round(rrarefy(t(otutabP), min_depth)))

mds <- metaMDS(t_otus_rarefied)

```

```{r}
mds$points %>% as.data.frame() %>% rownames_to_column("observation") %>% inner_join(mapping %>% mutate(Sample = as.character(Sample)), by =c("observation" = "Sample")) %>%
  ggplot(aes(MDS1, MDS2, color = SampleType, shape = Soil)) + geom_point(size = 2)

# %>%
#   gather("sample","value", -observation, -Soil, -SampleType, -Sampling_time, -Replicate, - SoilSample, -Replicate_no) %>%
#   ggplot(aes(x = SampleType, y = value)) + 
#   geom_jitter(aes(color = Replicate_no), alpha = 0.1) +
#   geom_boxplot(outlier.shape = NA, fill = "transparent") + 
#   geom_point(aes(color = Replicate_no), data = actual_richness, size = 3) +
#   facet_wrap(~Soil) +  theme(axis.text.x = element_text(angle = -90, hjust = 0),
#         axis.title.x = element_blank())
```

```{r}
set.seed(134524223)
#resampled_otu <- sample_posterior_dm_all(10, t_otutab, prior = 0.5, N_draws = "original") 
resampled_otu <- sample_posterior_dm_all(20, t_otutab, prior = "empirical", N_draws = "original")
resampled_otu_flat <- flatten_posterior_samples(resampled_otu)
original_renamed <- t_otutab
rownames(original_renamed) <- paste0(rownames(original_renamed),"_","Orig")

resampled_mds <- metaMDS(rbind(original_renamed, resampled_otu_flat), trymax = 50)
```



```{r}
plot_samples_with_orig <- function(resampled_mds) {
  resampled_mds$points %>% as.data.frame() %>% rownames_to_column("observation_sample") %>%
    separate("observation_sample", c("observation","sample"), sep = "_")  %>% 
    inner_join(mapping %>% mutate(Sample = as.character(Sample)), by =c("observation" = "Sample")) %>%
    mutate(is_original = sample == "Orig") %>%
    ggplot(aes(MDS1, MDS2, color = SampleType, shape = Soil, size = is_original, alpha = is_original)) + geom_point() + scale_size_manual(values = c(1, 3)) + scale_alpha_manual(values = c(0.3,1))
}

plot_samples_with_orig(resampled_mds)
```

What happens when we take a small subset of the samples so that they are similar?

```{r}
selected_observations <- mapping %>% filter(SampleType == "Control", Soil == "Spruce") %>% pull("Sample") %>% as.character()

set.seed(82524521)
t_otutab_filtered <- t_otutab[selected_observations,, drop = FALSE]
resampled_otu_filtered <- sample_posterior_dm_all(20, t_otutab_filtered, prior = 0.5, N_draws = "original")
resampled_otu_filtered_flat <- flatten_posterior_samples(resampled_otu_filtered)
original_filtered_renamed <- t_otutab_filtered
rownames(original_filtered_renamed) <- paste0(rownames(original_filtered_renamed),"_","Orig")

resampled_mds_filtered <- metaMDS(rbind(original_filtered_renamed, resampled_otu_filtered_flat), trymax = 50)
```

```{r}
plot_samples_with_orig(resampled_mds_filtered)
```


## Using Stan

```{r}
model <- stan_model(here("dm.stan"))
```

```{r}
fit <- sampling(model, data = list(N = ncol(t_otutab), counts = t_otutab[1,]))
summary(fit, pars = "alpha_prior")$summary
guess <- alpha_guess_ml(t_otutab[1,])
guess
tibble(alpha_prior = rstan::extract(fit, pars = "alpha_prior")$alpha_prior) %>% ggplot(aes(alpha_prior)) + 
  geom_histogram(bins = 50) + geom_vline(xintercept = guess, color = "blue", size = 2)
```

```{r}
N_samples = 20
resampled_stan <- rstan::extract(fit)$counts_gen[1:N_samples,]
rownames(resampled_stan) <- paste0(rownames(t_otutab)[1],"_S",1:N_samples)
colnames(resampled_stan) <- colnames(t_otutab)

set.seed(5214322)
original_stan_renamed <- t_otutab[1,, drop = FALSE]
rownames(original_stan_renamed) <- paste0(rownames(original_stan_renamed),"_","Orig")

resampled_mds_stan <- metaMDS(rbind(original_stan_renamed, resampled_stan), trymax = 50)

```

```{r}
plot_samples_with_orig(resampled_mds_stan)
```


## Not working parts
Testing alternative priors, currently does not work

```{r}
set.seed(32146588)
#resampled_otu <- sample_posterior_dm_all(10, t_otutab, prior = 0.5, N_draws = "original") 
resampled_otu_2 <- sample_posterior_dm_all(20, t_otutab, prior = 0.5, N_draws = "original")
resampled_otu_flat_2 <- flatten_posterior_samples(resampled_otu)

resampled_mds_2 <- metaMDS(rbind(original_renamed, resampled_otu_flat_2), trymax = 50)
```
```{r}
plot_samples_with_orig(resampled_mds_2)
```

Sampling in latent space

```{r}
set.seed(8524362)
resampled_latent <- sample_latent_dm_all(10, t_otutab, prior = 0.5) 
resampled_latent_flat <- flatten_posterior_samples(resampled_otu)

resampled_mds_latent <- metaMDS(resampled_otu_flat, trymax = 60)
```



```{r}
resampled_mds_latent$points %>% as.data.frame() %>% rownames_to_column("observation_sample") %>%
  separate("observation_sample", c("observation","sample"), sep = "_")  %>% 
  inner_join(mapping %>% mutate(Sample = as.character(Sample)), by =c("observation" = "Sample")) %>%
  ggplot(aes(MDS1, MDS2, color = SampleType, shape = Soil) + geom_point() 
```
