---
title: "Tests against synthetic datasets"
output: html_notebook
---


```{r setup}
devtools::load_all()
library(tidyverse)
library(readxl)
library(here)
library(cowplot)
library(vegan)
output_dir <- here::here("local_temp_data")
if(!dir.exists(output_dir)) {
  dir.create(output_dir)
}
theme_set(cowplot::theme_cowplot())
#theme_update(panel.background = element_rect(fill = "#e0e0e0"))
```



```{r}
generate_regular <- function(N_sides, N_replicates = 1) {
  true_regular <- array(NA_real_, dim = c(N_sides, N_sides * 5))
  otus_regular <- array(NA_integer_, dim = c(N_sides * N_replicates, N_sides * 5))
  
  regular_mapping <- data.frame(Sample = as.character(1:(N_sides * N_replicates)), Group = rep(as.character((1:N_sides)), each = N_replicates))
  
  for(i in 1:N_sides) {
    other_indices = (1:N_sides)[-i]
    true_regular[i, i] <- 50
    true_regular[i, other_indices] <- 10
    true_regular[i, i + N_sides] <- 0.1
    true_regular[i, other_indices + N_sides] <- 8
    true_regular[i, i + N_sides * 2] <- 3
    true_regular[i, other_indices + N_sides * 2] <- 0.1
    true_regular[i, i + N_sides * 3] <- 2
    true_regular[i, other_indices + N_sides * 3] <- 0.1
    true_regular[i, i + N_sides * 4] <- 1
    true_regular[i, other_indices + N_sides * 4] <- 0.1
    
    for(otu in which(regular_mapping$Group == as.character(i))) {
      noisy_mean <- true_regular[i,] * rlnorm(N_sides * 5, meanlog = 0, sdlog = 0.1)
      otus_regular[otu, ] <- rmultinom(1, N_sides * 200, noisy_mean) 
    }
  }
  
  
  list(true = true_regular, otus = otus_regular, mapping = regular_mapping)
}

regular_4 <- generate_regular(4)

#vegdist(otus_regular)

sens_regular <- mds_sensitivity_check(regular_4$otus, regular_4$mapping)
```
```{r}
plot.mds_sensitivity(sens_regular, color_aes = Group)
plot.mds_sensitivity(sens_regular, color_aes = Group, variability = "facet")
```

```{r}
regular_4_5 <- generate_regular(4, N_replicates = 5)

sens_regular_4_5 <- mds_sensitivity_check(regular_4_5$otus, regular_4_5$mapping)
```
```{r}
plot.mds_sensitivity(sens_regular_4_5, color_aes = Group)
plot.mds_sensitivity(sens_regular_4_5, color_aes = Group, variability = "facet")
```
```{r}
sens_regular_4_5_jk <- mds_sensitivity_check(regular_4_5$otus, regular_4_5$mapping, 
                                             bootstrap_func = bootstrap_reads_jackknife_observations)

plot.mds_sensitivity(sens_regular_4_5_jk, color_aes = Group)

```



