---
title: "MDS Subsampling experiment"
output: html_notebook
---


```{r setup}
devtools::load_all()
library(tidyverse)
library(readxl)
library(here)
library(cowplot)
library(vegan)
theme_set(theme_cowplot())
output_dir <- here::here("local_temp_data")
if(!dir.exists(output_dir)) {
  dir.create(output_dir)
}

metagenboot_options(cores = 10)
```


```{r load data}
datasets <- list()

otus_raw_gp <- read.csv(here("local_data","gp2017.txt"), stringsAsFactors = FALSE, sep = "\t")
#otu_tab <- otus_raw %>% as.data.frame() %>% column_to_rownames("X__1") %>% as.matrix()
otu_tab_gp <- otus_raw_gp %>% select(B005_B006:T199_T200) %>% as.matrix() %>% t()
otu_tab_gp <- otu_tab_gp[rowSums(otu_tab_gp) > 2000 & rownames(otu_tab_gp) != "B005_B006",]

mapping_gp <- tibble(Sample = rownames(otu_tab_gp)) %>% mutate(Origin = if_else(grepl("^B", Sample), "Panama", if_else(grepl("^L", Sample), "Costa Rica", "Ecuador")))

```


```{r}
set.seed(20191107)

gp_run_file <- paste0(output_dir,"/run_gp_varying.rds")
if(!file.exists(gp_run_file)) {
  experiment_gp_run <- run_mds_experiment(
    otu_tab = otu_tab_gp,
    bootstrap_func = bootstrap_func_dm(20),
    n_observations_to_use_min = 15,
    n_observations_to_use_max = 60,
    n_steps = 100,
    mapping = mapping_gp,
    accept_subset_func = function(mapping_filtered) {
                      group_counts <- mapping_filtered %>% group_by(Origin) %>% summarise(count = n(), .groups = "drop")
                      nrow(group_counts) == 3 && all(group_counts$count > 2)
                   })
  
  saveRDS(experiment_gp_run, file = gp_run_file)
} else {
  experiment_gp_run <- readRDS(file = gp_run_file)
}
```

```{r}
experiment_gp <- eval_mds_experiment(experiment_gp_run, Origin)
experiment_gp$per_point <- experiment_gp$per_point %>% mutate(min_nobs = min(n_observations), n_observations_norm = (n_observations - min_nobs) / (max(n_observations) - min_nobs))
experiment_gp$global <- experiment_gp$global %>% mutate(min_nobs = min(n_observations), n_observations_norm = (n_observations - min_nobs) / (max(n_observations) - min_nobs))

```


```{r}
my_plot <- function(data, x,y, color = NULL, shape = NULL, alpha = 1, group = 1) {
  x <- enquo(x)
  y <- enquo(y)
  color <- enquo(color)
  shape <- enquo(shape)
  group <- enquo(group)
  ggplot(data, aes(!!x, !!y, color = !!color, shape = !!shape, group = !! group)) + geom_jitter(width = 0, height = 0, alpha = alpha) + geom_smooth(method = "lm") + scale_color_distiller(palette = "Spectral")
}

# stats %>% my_plot(n_samples, rmse)
# stats %>% my_plot(min_connectivity_average, rmse)
# stats %>% my_plot(avg_connectivity_average, rmse)
# stats %>% my_plot(min_connectivity_min, rmse)
# stats %>% my_plot(avg_connectivity_min, rmse)


```

```{r}
#experiment_gp$per_point %>% filter(step %in% c(81,sample(step, 5))) %>% my_plot(location, location_error, step, shape = factor(step))
experiment_gp$per_point %>% my_plot(location, location_error, n_observations)
experiment_gp$per_point %>% my_plot(distances, rmse_distances, n_observations)
experiment_gp$per_point %>% my_plot(angles, rmse_angles, n_observations)
```

```{r}
lm(location_error ~ location + n_observations_norm, data = experiment_gp$per_point)
lm(rmse_distances ~ distances + n_observations_norm, data = experiment_gp$per_point)
lm(rmse_angles ~ angles + n_observations_norm, data = experiment_gp$per_point)
```


```{r}
experiment_gp$global %>% my_plot(n_observations, rmse_distances)

```

```{r}
experiment_gp$per_point %>% group_by(step, n_observations) %>% summarise(consistency_location = 1 - sqrt(sum((1 - location)^2) / (unique(n_observations) - 1)), .groups = "drop") %>%   inner_join(experiment_gp$global %>% select(-consistency_location, -n_observations), by = c("step" = "step")) %>%
  my_plot(consistency_location, rmse_location, n_observations)
```


```{r}
experiment_gp$global %>% my_plot(consistency_location, rmse_location, n_observations)
experiment_gp$global %>% my_plot(consistency_distances, rmse_distances, n_observations) 
experiment_gp$global %>% my_plot(consistency_angles, rmse_angles, n_observations) 
```

```{r}
lm(rmse_location ~ consistency_location, data = experiment_gp$global)
lm(rmse_location ~ consistency_location + n_observations_norm, data = experiment_gp$global)
lm(rmse_distances ~ consistency_distances, data = experiment_gp$global)
lm(rmse_distances ~ consistency_distances + n_observations_norm, data = experiment_gp$global)
lm(rmse_angles ~ consistency_angles, data = experiment_gp$global)
lm(rmse_angles ~ consistency_angles + n_observations_norm, data = experiment_gp$global)

```


```{r}
experiment_gp$global %>% filter(consistency_location < 0.3)
plot(experiment_gp$sens_checks[[81]], color_aes = Origin, shape_aes = Origin)

```

```{r}
test_mds <- metaMDS(experiment_gp$step_results[[81]]$otu_tab_filtered, scaling = TRUE)
plot_mds(test_mds)
test_mds
test_mds$points %>% colMeans()
test_mds$points %>% colMeans() %>% rep(each = 10) %>% matrix(ncol = 2)
```


```{r}
max(dist(experiment_gp$sens_checks[[32]]$base_mds$points, method = "euclidean"))
max(dist(experiment_gp$sens_checks[[10]]$base_mds$points, method = "euclidean"))
max(dist(experiment_gp$sens_checks[[33]]$base_mds$points, method = "euclidean"))
experiment_gp$sens_checks[[10]]$base_mds$points ^ 2 %>% rowSums() %>% mean() %>% sqrt()
experiment_gp$sens_checks[[32]]$base_mds$points ^ 2 %>% rowSums() %>% mean() %>% sqrt()

```


```{r}
otus_raw_geel <- read_excel(here("private_data","vanGeel2017.xlsx"), sheet = "Sample OTU matrix")
otu_tab_geel <- otus_raw_geel %>% select(OTU_16:OTU_5257) %>% as.matrix()

mapping_geel <- otus_raw_geel %>% select(species_id:plot) %>% mutate(Sample = paste0("S_",1:n()), type = if_else(species_id == "soil", "Soil", "Root"))

rownames(otu_tab_geel) <- mapping_geel$Sample

```


```{r}
set.seed(201911072)

geel_run_file <- paste0(output_dir,"/run_geel_varying.rds")
if(!file.exists(geel_run_file)) {
  experiment_geel_run <- run_mds_experiment(
    otu_tab = otu_tab_geel,
    bootstrap_func = bootstrap_func_dm(20),
    n_observations_to_use_min = 10,
    n_observations_to_use_max = 60,
    n_steps = 100,
    mapping = mapping_geel,
    accept_subset_func = function(mapping_filtered) {
       group_counts <- mapping_filtered %>% group_by(grassland_type) %>% summarise(count = n())
       nrow(group_counts) == 2 && all(group_counts$count > 2)
    }
  )
  
  saveRDS(experiment_geel_run, file = geel_run_file)
} else {
  experiment_geel_run <- readRDS(file = geel_run_file)
}

```

```{r}
experiment_geel <- eval_mds_experiment(experiment_geel_run, grassland_type)
```


```{r}
experiment_geel$per_point %>% my_plot(location, location_error, n_observations)
experiment_geel$per_point %>% my_plot(distances, rmse_distances, n_observations)
experiment_geel$per_point %>% my_plot(angles, rmse_angles, n_observations)
```


```{r}
experiment_geel$global %>% my_plot(consistency_location, rmse_location, n_observations)
experiment_geel$global %>% my_plot(consistency_distances, rmse_distances, n_observations) 
experiment_geel$global %>% my_plot(consistency_angles, rmse_angles, n_observations) 

```

```{r}
lm(location_error ~ location + n_observations, data = experiment_geel$per_point)
lm(rmse_distances ~ distances + n_observations, data = experiment_geel$per_point)
lm(rmse_angles ~ angles + n_observations, data = experiment_geel$per_point)

```


```{r}
set.seed(201911072)

geel_jn_run_file <- paste0(output_dir,"/run_geel_jn_varying.rds")
if(!file.exists(geel_jn_run_file)) {
  experiment_geel_jn_run <- run_mds_experiment(
    otu_tab = otu_tab_geel,
    bootstrap_func = bootstrap_reads_jackknife_observations,
    n_observations_to_use_min = 10,
    n_observations_to_use_max = 60,
    n_steps = 100,
    mapping = mapping_geel,
    accept_subset_func = function(mapping_filtered) {
       group_counts <- mapping_filtered %>% group_by(grassland_type) %>% summarise(count = n())
       nrow(group_counts) == 2 && all(group_counts$count > 2)
    }
  )
  
  saveRDS(experiment_geel_jn_run, file = geel_jn_run_file)
} else {
  experiment_geel_jn_run <- readRDS(file = geel_jn_run_file)
}
```

```{r}
experiment_geel_jn <- eval_mds_experiment(experiment_geel_jn_run, grassland_type)
```

```{r}
experiment_geel_jn$per_point %>% my_plot(location, location_error, n_observations)
experiment_geel_jn$per_point %>% my_plot(distances, rmse_distances, n_observations)
experiment_geel_jn$per_point %>% my_plot(angles, rmse_angles, n_observations)

```

```{r}
lm(location_error ~ location + n_observations, data = experiment_geel_jn$per_point)
lm(rmse_distances ~ distances + n_observations, data = experiment_geel_jn$per_point)
lm(rmse_angles ~ angles + n_observations, data = experiment_geel_jn$per_point)


```


```{r}
experiment_geel_jn$global %>% my_plot(consistency_location, rmse_location, n_observations)
experiment_geel_jn$global %>% my_plot(consistency_distances, rmse_distances, n_observations) 
experiment_geel_jn$global %>% my_plot(consistency_angles, rmse_angles, n_observations) 

```


## Phyloseq examples

```{r}
data("GlobalPatterns")
GP = prune_taxa(taxa_sums(GlobalPatterns)>0, GlobalPatterns)
mapping_gp <- GP@sam_data %>% as_tibble() %>% mutate(Sample = X.SampleID)
otu_tab_gp <- as.matrix(t(GP@otu_table))
```


```{r}
set.seed(20210211)

gp_run_file <- paste0(output_dir,"/run_global_patterns_varying.rds")
if(!file.exists(gp_run_file)) {
  experiment_gp_run <- run_mds_experiment(
    otu_tab = otu_tab_gp,
    bootstrap_func = bootstrap_func_dm(20),
    n_observations_to_use_min = 15,
    n_observations_to_use_max = 20,
    n_steps = 100,
    mapping = mapping_gp,
    accept_subset_func = function(mapping_filtered) {
      TRUE
                   })
  
  saveRDS(experiment_gp_run, file = gp_run_file)
} else {
  experiment_gp_run <- readRDS(file = gp_run_file)
}
```

```{r}
experiment_gp <- eval_mds_experiment(experiment_gp_run, 1)
experiment_gp$per_point <- experiment_gp$per_point %>% mutate(min_nobs = min(n_observations), n_observations_norm = (n_observations - min_nobs) / (max(n_observations) - min_nobs))
experiment_gp$global <- experiment_gp$global %>% mutate(min_nobs = min(n_observations), n_observations_norm = (n_observations - min_nobs) / (max(n_observations) - min_nobs))

```
